import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `chat_model.dart` with the code generated by Freezed
part 'chat_model.freezed.dart';
// optional: Since our chatModel class is serializable, we must add this line.
// But if chatModel was not serializable, we could skip it.
part 'chat_model.g.dart';

///Model for database chat

class TimestampConverter implements JsonConverter<DateTime, Timestamp> {
  const TimestampConverter();

  @override
  DateTime fromJson(Timestamp json) => json.toDate();

  @override
  Timestamp toJson(DateTime object) => Timestamp.fromDate(object);
}

class TimestampNullableConverter implements JsonConverter<DateTime?, Timestamp?> {
  const TimestampNullableConverter();

  @override
  DateTime? fromJson(Timestamp? json) => json?.toDate();

  @override
  Timestamp? toJson(DateTime? object) =>
      object == null ? null : Timestamp.fromDate(object);
}

@freezed
class ChatModel with _$ChatModel {
  const factory ChatModel(
      {@TimestampConverter() DateTime? timestamp,
      required String fieldID,
      required String displayName,
      required String message,
      required String uid,
      required String tripDocID,
      required Map<String,bool> status}) = _ChatModel;

              factory ChatModel.fromJson(Map<String, Object?> json)
      => _$ChatModelFromJson(json);
}
