import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `lodging_model.dart` with the code generated by Freezed
part 'lodging_model.freezed.dart';
// optional: Since our lodgingModel class is serializable, we must add this line.
// But if lodgingModel was not serializable, we could skip it.
part 'lodging_model.g.dart';

///Model for database lodging

class TimestampConverter implements JsonConverter<DateTime, Timestamp> {
  const TimestampConverter();

  @override
  DateTime fromJson(Timestamp json) => json.toDate();

  @override
  Timestamp toJson(DateTime object) => Timestamp.fromDate(object);
}

class TimestampNullableConverter
    implements JsonConverter<DateTime?, Timestamp?> {
  const TimestampNullableConverter();

  @override
  DateTime? fromJson(Timestamp? json) => json?.toDate();

  @override
  Timestamp? toJson(DateTime? object) =>
      object == null ? null : Timestamp.fromDate(object);
}

@freezed
class LodgingModel with _$LodgingModel {
  const factory LodgingModel(
      {required String endTime,
      required String startTime,
      @TimestampConverter() DateTime? startDateTimestamp,
      @TimestampConverter() DateTime? endDateTimestamp,
      required String location,
      required String comment,
      required String displayName,
      required String fieldID,
      required String link,
      required String lodgingType,
      required String uid,
      required List<String> voters}) = _LodgingModel;

  factory LodgingModel.fromJson(Map<String, Object?> json) =>
      _$LodgingModelFromJson(json);

  factory LodgingModel.mock() {
    return LodgingModel(
      endTime: '10:00 PM',
      startTime: '3:00 PM',
      startDateTimestamp: DateTime(2023, 5),
      endDateTimestamp: DateTime(2023, 5, 5),
      location: 'City X',
      comment: 'Beautiful and luxurious hotel.',
      displayName: 'Hotel X',
      fieldID: 'lodging123',
      link: 'https://example.com/hotel-x',
      lodgingType: 'Hotel',
      uid: 'user123',
      voters: <String>['userA', 'userB', 'userC'],
    );
  }
}
