---
name: travelcrew
description: First Flutter App
version: 3.0.0+60
publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_link_preview:
    path: packages/flutter_link_preview
  gfsearchbar:
    path: packages/gfsearchbar
  flappy_search_bar:
    path: packages/flappy_search_bar
  add_2_calendar: ^2.1.0
  animations: ^2.0.1
  auto_size_text: ^2.1.0
  bloc: ^7.0.0
  clipboard: ^0.1.3
  cloud_firestore: ^2.0.0
  cloud_functions: ^1.0.6
  curved_navigation_bar: ^0.4.0-nullsafety.0
  draggable_scrollbar: ^0.1.0
  equatable: ^2.0.3
  expandable: ^5.0.1
  firebase_analytics: ^8.0.3
  firebase_auth: ^1.1.1
  firebase_core: ^1.1.0
  firebase_crashlytics: ^2.0.2
  firebase_messaging: ^9.1.3
  firebase_performance: ^0.7.0+2
  firebase_storage: ^8.0.5
  flutter_animation_progress_bar: ^2.0.0
  flutter_app_badger: ^1.2.0
  flutter_bloc: ^7.0.1
  flutter_dotenv: ^5.0.0
  flutter_google_places: ^0.3.0
  flutter_link_previewer: ^2.0.0
  flutter_linkify: ^5.0.2
  flutter_local_notifications: ^5.0.0+4
  flutter_spinkit: ^5.0.0
  fluttertoast: ^8.0.6
  geocoding: ^2.0.0
  geolocator: ^7.0.3
  get_it: ^7.1.1
  google_sign_in: ^5.0.2
  http: ^0.13.3
  image_cropper: ^1.4.0
  image_picker: ^0.7.4
  in_app_review: ^2.0.2
  intl: ^0.17.0
  maps_launcher: ^2.0.0
  modal_bottom_sheet: ^2.0.0
  multiple_stream_builder: ^2.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  sign_in_with_apple: ^3.0.0
  sizer: ^2.0.13
  showcaseview: ^1.1.0
  social_share: ^2.1.1
  syncfusion_flutter_gauges: ^19.1.59
  theme_provider: ^0.5.0
  url_launcher: ^6.0.3
  webview_flutter: ^2.0.4
  cupertino_icons: ^1.0.3
  rxdart: ^0.26.0
  observable: ^0.23.0
  eva_icons_flutter: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - ./.env
  - assets/images/
  fonts:
  - family: Raleway
    fonts:
    - asset: assets/fonts/Raleway-VariableFont_wght.ttf
  - family: Cantata One
    fonts:
    - asset: assets/fonts/CantataOne-Regular.ttf
  - family: RockSalt
    fonts:
    - asset: assets/fonts/RockSalt-Regular.ttf
  - family: Lato Black
    fonts:
    - asset: assets/fonts/Lato-Black.ttf
  - family: Playfair
    fonts:
    - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf
    - asset: assets/fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
      style: italic
