name: travelcrew
description: First Flutter App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.0+21

dependencies:
  flutter:
    sdk: flutter
  add_2_calendar: ^1.4.0
  intl: ^0.16.1
  image_picker: ^0.6.7+11
  webview_flutter: ^1.0.5
  cloud_firestore: ^0.14.2
  cloud_functions: ^0.6.0+1
  device_calendar: ^3.1.0
  firebase_core: ^0.5.1
  firebase_analytics: ^6.1.0
  firebase_auth: ^0.18.2
  firebase_crashlytics: ^0.2.2
  flutter_google_places: ^0.2.6
  firebase_messaging: ^7.0.3
  firebase_performance: ^0.4.0+2
  firebase_storage: ^4.0.1
  fluttertoast: ^7.1.1
  flutter_app_badger: ^1.1.2
  flutter_local_notifications: ^2.0.0
  flutter_linkify: ^3.1.3
  flutter_spinkit: ^4.1.2+1
  geolocator: ^6.1.3
  geocoding: ^1.0.5
  get_it: ^5.0.1
  google_sign_in: ^4.5.5
  provider: ^4.3.2+2
  http: ^0.12.2
  draggable_scrollbar: ^0.0.4
  flappy_search_bar: ^1.7.2
  modal_bottom_sheet: ^0.2.2
  apple_sign_in: ^0.1.0
  url_launcher: ^5.7.5


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Raleway
     fonts:
       - asset: assets/fonts/Raleway-VariableFont_wght.ttf
#       - weight: 400
#       - asset: assets/fonts/Raleway-Italic-VariableFont_wght.ttf
#         style: italic
   - family: Cantata One
     fonts:
       - asset: assets/fonts/CantataOne-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
   - family: RockSalt
     fonts:
       - asset: assets/fonts/RockSalt-Regular.ttf

   - family: Lato Black
     fonts:
       - asset: assets/fonts/Lato-Black.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
