---
name: travelcrew
description: First Flutter App
version: 3.0.6+70
publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  # API
  http: ^0.13.3
  oauth2_client: ^2.2.6
  splitwise_api: ^2.0.3
  flutter_google_places: ^0.3.0
  geocoding: ^2.0.0
  geolocator: ^7.0.3

  # Auth
  google_sign_in: ^5.0.2
  sign_in_with_apple: ^3.0.0

  # Data
  faker: ^2.0.0
  flutter_dotenv: ^5.0.2
  grouped_list: ^4.1.0
  multiple_stream_builder: ^2.0.0
  shared_preferences: ^2.0.5
  sticky_grouped_list: ^1.3.0

  # Features
  add_2_calendar: ^2.1.1
  clipboard: ^0.1.3
  in_app_review: ^2.0.2

  # Firebase
  cloud_firestore: ^2.5.3
  cloud_functions: ^3.0.3
  firebase_analytics: ^8.3.2
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
  firebase_messaging: ^10.0.7
  firebase_performance: ^0.7.1+1
  firebase_storage: ^10.0.3

  # Images
  image_cropper: ^1.4.0
  image_picker: ^0.7.4

  # Notifications
  flutter_app_badger: ^1.3.0
  flutter_local_notifications: ^5.0.0+4
  fluttertoast: ^8.0.6
  notification_permissions: ^0.6.1

  # State Management
  bloc: ^7.0.0
  equatable: ^2.0.3
  flutter_bloc: ^7.2.0
  get_it: ^7.2.0
  observable: ^0.23.0
  provider: ^6.0.0

  # Self Packaged
  flutter_link_preview:
    path: packages/flutter_link_preview
  gfsearchbar:
    path: packages/gfsearchbar
  flappy_search_bar:
    path: packages/flappy_search_bar

  # Web
  flutter_link_previewer: ^2.0.0
  flutter_linkify: ^5.0.2
  maps_launcher: ^2.0.0
  url_launcher: ^6.0.3
  webview_flutter: ^2.0.4

  # UI
  animations: ^2.0.1
  auto_size_text: ^2.1.0
  cupertino_icons: ^1.0.3
  curved_navigation_bar: ^1.0.1
  draggable_scrollbar: ^0.1.0
  eva_icons_flutter: ^3.0.2
  expandable: ^5.0.1
  flutter_animation_progress_bar: ^2.0.0
  flutter_spinkit: ^5.0.0
  modal_bottom_sheet: ^2.0.0
  responsive_framework: ^0.1.4
  rxdart: ^0.26.0
  sizer: ^2.0.13
  syncfusion_flutter_gauges: ^19.1.59


  # Other
  intl: ^0.17.0
  nil: ^1.1.1
  showcaseview: ^1.1.0
#  social_share: ^2.1.1
#  lint: ^1.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
  - ./.env
  - assets/images/
  fonts:
  - family: Raleway
    fonts:
    - asset: assets/fonts/Raleway-VariableFont_wght.ttf
  - family: Cantata One
    fonts:
    - asset: assets/fonts/CantataOne-Regular.ttf
  - family: RockSalt
    fonts:
    - asset: assets/fonts/RockSalt-Regular.ttf
  - family: Lato Black
    fonts:
    - asset: assets/fonts/Lato-Black.ttf
  - family: Playfair
    fonts:
    - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf
    - asset: assets/fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
      style: italic
