name: travel_crew
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Firebase
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  firebase_storage: ^13.3.0
  firebase_messaging: ^16.2.0
  firebase_crashlytics: ^5.2.0
  cloud_functions: ^6.2.0

  # Authentication
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  googleapis_auth: ^2.0.0

  # Device & System Features
  image_picker: ^1.2.1
  file_picker: ^11.0.2
  video_player: ^2.10.1
  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.0
  geocoding: ^4.0.0
  permission_handler: ^12.0.1
  flutter_local_notifications: ^21.0.0

  # UI
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  intl_phone_field: ^3.2.0
  photo_view: ^0.15.0
  readmore: ^3.0.0
  google_fonts: ^8.0.2
  country_picker: ^2.0.27
  pinput: ^6.0.2
  mobkit_dashed_border: ^0.0.7
  modal_progress_hud_nsn: ^0.5.1
  flutter_swipe_action_cell: ^3.1.6
  custom_rating_bar: ^3.0.0
  timelines_plus: ^2.0.0
  flutter_quill: ^11.5.0
  dotted_border: ^3.1.0
  blur: ^4.0.2
  blurrycontainer: ^2.1.0
  syncfusion_flutter_datepicker: ^33.2.3
  table_calendar: ^3.1.3
  lucide_icons: ^0.257.0
  awesome_snackbar_content: ^0.1.5
  animated_splash_screen: ^1.3.0

  # State Management
  get: ^4.7.3

  # Utilities & Helpers
  share_plus: ^12.0.2
  flutter_dotenv: ^6.0.1
  flutter_secure_storage: ^10.0.0

  # Development/Build Utilities
  change_app_package_name: ^1.5.0 



  uuid: ^4.5.3
  http: ^1.6.0
  collection: ^1.19.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/img_app_logo.png"
  min_sdk_android: 21 
