---
name: travelcrew
description: Travel Crew is a mobile app for friends to share travel plans, organize travel and even create full itineraries together.
version: 3.1.0+77
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # API
  http: ^0.13.5
  oauth2_client: ^3.0.0
  google_places_flutter: ^2.0.5
  geocoding: ^2.0.4
  geolocator: ^9.0.1

  # Auth
  google_sign_in: ^5.4.1
  sign_in_with_apple: ^4.1.0

  # Data
  faker: ^2.0.0
  flutter_dotenv: ^5.0.2
  grouped_list: ^5.1.2
  multiple_stream_builder: ^3.0.2
  shared_preferences: ^2.0.15
  sticky_grouped_list: ^3.1.0

  # Features
  add_2_calendar: ^2.2.3
  clipboard: ^0.1.3
  in_app_review: ^2.0.4
  showcaseview: ^2.0.0+1

  # Firebase
  cloud_firestore: ^4.3.1
  cloud_functions: ^4.0.7
  firebase_analytics: ^10.1.0
  firebase_auth: ^4.2.4
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.9
  firebase_messaging: ^14.2.1
  firebase_performance: ^0.9.0+9
  firebase_storage: ^11.0.10

  # Images
  image_cropper: ^3.0.1
  image_picker: ^0.8.5+3

  # Notifications
  flutter_app_badger: ^1.4.0
  flutter_local_notifications: ^13.0.0
  fluttertoast: ^8.0.9
  notification_permissions: ^0.6.1

  # State Management
  bloc: ^8.1.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  observable: ^0.24.0
  provider: ^6.0.2

  # Self Packaged
  flappy_search_bar:
    path: packages/flappy_search_bar

  # Web
  any_link_preview: ^3.0.0
  flutter_linkify: ^5.0.2
  url_launcher: ^6.1.2
  webview_flutter: ^4.0.1

  # UI
  animated_splash_screen: ^1.3.0
  animations: ^2.0.7
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.5
  curved_navigation_bar: ^1.0.3
  draggable_scrollbar: ^0.1.0
  eva_icons_flutter: ^3.1.0
  expandable: ^5.0.1
  flutter_animation_progress_bar: ^2.1.1
  flutter_spinkit: ^5.1.0
  modal_bottom_sheet: ^2.0.1
  responsive_framework: ^0.2.0
  rxdart: ^0.27.5
  sizer: ^2.0.15
  syncfusion_flutter_gauges: ^20.2.43

  # Other
  intl: ^0.17.0
  nil: ^1.1.1
  cached_network_image: ^3.2.3
  # flutter_sms: 
  #   git:
  #     url: https://github.com/prasadsunny1/flutter_sms.git

#  social_share: ^2.1.1
#  lint: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_intl:
  enabled: true

flutter:
  generate: true
  uses-material-design: true
  assets:
  - ./.env
  - assets/images/
  fonts:
  - family: Raleway
    fonts:
    - asset: assets/fonts/Raleway-VariableFont_wght.ttf
  - family: Cantata One
    fonts:
    - asset: assets/fonts/CantataOne-Regular.ttf
  - family: RockSalt
    fonts:
    - asset: assets/fonts/RockSalt-Regular.ttf
  - family: Lato Black
    fonts:
    - asset: assets/fonts/Lato-Black.ttf
  - family: Playfair
    fonts:
    - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf
    - asset: assets/fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
      style: italic


