import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `recommended_model.dart` with the code generated by Freezed
part 'recommended_model.freezed.dart';
// optional: Since our recommendedModel class is serializable, we must add this line.
// But if recommendedModel was not serializable, we could skip it.
part 'recommended_model.g.dart';

class TimestampConverter implements JsonConverter<DateTime, Timestamp> {
  const TimestampConverter();

  @override
  DateTime fromJson(Timestamp json) => json.toDate();

  @override
  Timestamp toJson(DateTime object) => Timestamp.fromDate(object);
}

class TimestampNullableConverter implements JsonConverter<DateTime?, Timestamp?> {
  const TimestampNullableConverter();

  @override
  DateTime? fromJson(Timestamp? json) => json?.toDate();

  @override
  Timestamp? toJson(DateTime? object) =>
      object == null ? null : Timestamp.fromDate(object);
}

@freezed
class RecommendedContentModel with _$RecommendedContentModel {
  const factory RecommendedContentModel(
      {required String name,
      required int clicks,
      @TimestampConverter() DateTime? dateCreated,
      required String docID,
      required List<String> urlToImage}) = _RecommendedContentModel;

        factory RecommendedContentModel.fromJson(Map<String, Object?> json)
      => _$RecommendedContentModelFromJson(json);
}
