import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `members_model.dart` with the code generated by Freezed
part 'member_model.freezed.dart';
// optional: Since our membersModel class is serializable, we must add this line.
// But if membersModel was not serializable, we could skip it.
part 'member_model.g.dart';

//Model for database members

@freezed
class MemberModel with _$MemberModel {
  const factory MemberModel(
      {required String displayName,
      required String firstName,
      required String lastName,
      required String uid,
      required String urlToImage}) = _MemberModel;

        factory MemberModel.fromJson(Map<String, Object?> json)
      => _$MemberModelFromJson(json);
}
