import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `chat_model.dart` with the code generated by Freezed
part 'dm_chat_model.freezed.dart';
// optional: Since our chatModel class is serializable, we must add this line.
// But if chatModel was not serializable, we could skip it.
part 'dm_chat_model.g.dart';

///Model for database chat

class TimestampConverter implements JsonConverter<DateTime, Timestamp> {
  const TimestampConverter();

  @override
  DateTime fromJson(Timestamp json) => json.toDate();

  @override
  Timestamp toJson(DateTime object) => Timestamp.fromDate(object);
}

class TimestampNullableConverter implements JsonConverter<DateTime?, Timestamp?> {
  const TimestampNullableConverter();

  @override
  DateTime? fromJson(Timestamp? json) => json?.toDate();

  @override
  Timestamp? toJson(DateTime? object) =>
      object == null ? null : Timestamp.fromDate(object);
}

@freezed
class DMChatModel with _$DMChatModel {
  const factory DMChatModel(
      {@TimestampConverter() DateTime? timestamp,
      required String fieldID,
      required String message,
      required String senderID,
      required String receiverID,
      required List<String> readBy}) = _DMChatModel;

              factory DMChatModel.fromJson(Map<String, Object?> json)
      => _$DMChatModelFromJson(json);
}