import 'package:get/get.dart';
class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      "09:41": "09:41",
      "Reviews": "Reviews",
      "All": "All",
      "1": "1",
      "2": "2",
      "3": "3",
      "4": "4",
      "5": "5",
      "Kurt Mullins": "Kurt Mullins",
      "10 mins ago": "10 mins ago",
      "Filter Products": "Filter Products",
      "Sort By": "Sort By",
      "Newest": "Newest",
      "Popular": "Popular",
      "Oldest": "Oldest",
      "category": "category",
      "Categories": "Categories",
      "Electronics": "Electronics",
      "Automotive": "Automotive",
      "Clothing": "Clothing",
      "Furniture Stuff": "Furniture Stuff",
      "Personal Care": "Personal Care",
      "More +": "More +",
      "Color": "Color",
      "Black": "Black",
      "Blue": "Blue",
      "Purple": "Purple",
      "Green": "Green",
      "XS": "XS",
      "S": "S",
      "M": "M",
      "L": "L",
      "XL": "XL",
      "XXL": "XXL",
      "By Price": "By Price",
      "High-to-Low": "High-to-Low",
      "Low-to-High": "Low-to-High",
      "Rating": "Rating",
      "Reset": "Reset",
      "Apply": "Apply",
      "QUIT SMOKE": "QUIT SMOKE",
      "Added to Cart": "Added to Cart",
      "Details": "Details",
      "View Cart": "View Cart",
      "Sherpa Sleeve": "Sherpa Sleeve",
      "50.00": "\$50.00",
      "Size": "Size",
      "Add to Cart": "Add to Cart",
      "View Profile": "View Profile",
      "Start Chat": "Start Chat",
      "Cash on delivery": "Cash on delivery",
      "Non-Refundable": "Non-Refundable",
      "Cancelable": "Cancelable",
      "description": "description",
      "Buy Now": "Buy Now",
      "Request to Buy": "Request to Buy",
      "Notification": "Notification",
      "Success Notification!": "Success Notification!",
      "Warning Notification": "Warning Notification",
    },
    'ar_SA': {
      "09:41": "09:41",
      "Reviews": "التعليقات",
      "All": "الكل",
      "1": "١",
      "2": "٢",
      "3": "٣",
      "4": "٤",
      "5": "٥",
      "Kurt Mullins": "كيرت مولينز",
      "10 mins ago": "منذ 10 دقائق",
      "Filter Products": "تصفية المنتجات",
      "Sort By": "الترتيب حسب",
      "Newest": "الأحدث",
      "Popular": "الشائع",
      "Oldest": "الأقدم",
      "category": "الفئة",
      "Categories": "الفئات",
      "Electronics": "إلكترونيات",
      "Automotive": "السيارات",
      "Clothing": "ملابس",
      "Furniture Stuff": "الأثاث",
      "Personal Care": "العناية الشخصية",
      "More +": "المزيد +",
      "Color": "اللون",
      "Black": "أسود",
      "Blue": "أزرق",
      "Purple": "أرجواني",
      "Green": "أخضر",
      "XS": "XS",
      "S": "S",
      "M": "M",
      "L": "L",
      "XL": "XL",
      "XXL": "XXL",
      "By Price": "حسب السعر",
      "High-to-Low": "مرتفع إلى منخفض",
      "Low-to-High": "منخفض إلى مرتفع",
      "Rating": "التقييم",
      "Reset": "إعادة تعيين",
      "Apply": "تطبيق",
      "QUIT SMOKE": "الإقلاع عن التدخين",
      "Added to Cart": "أُضيف إلى العربة",
      "Details": "التفاصيل",
      "View Cart": "عرض العربة",
      "Sherpa Sleeve": "كم شيربا",
      "50.00": "50.00",
      "Size": "الحجم",
      "Add to Cart": "أضف إلى العربة",
      "View Profile": "عرض الملف الشخصي",
      "Start Chat": "ابدأ الدردشة",
      "Cash on delivery": "الدفع عند الاستلام",
      "Non-Refundable": "غير قابل للاسترداد",
      "Cancelable": "يمكن الإلغاء",
      "description": "الوصف",
      "Buy Now": "اشترِ الآن",
      "Request to Buy": "طلب الشراء",
      "Notification": "إشعار",
      "Success Notification!": "إشعار نجاح!",
      "Warning Notification": "إشعار تحذيري",
    },
  };
}
