import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `cost_object_model.dart` with the code generated by Freezed
part 'cost_object_model.freezed.dart';
// optional: Since our cost_objectModel class is serializable, we must add this line.
// But if cost_objectModel was not serializable, we could skip it.
part 'cost_object_model.g.dart';

///Model for database cost_object

///Model for cost_object data
class TimestampConverter implements JsonConverter<DateTime, Timestamp> {
  const TimestampConverter();

  @override
  DateTime fromJson(Timestamp json) => json.toDate();

  @override
  Timestamp toJson(DateTime object) => Timestamp.fromDate(object);
}

class TimestampNullableConverter implements JsonConverter<DateTime?, Timestamp?> {
  const TimestampNullableConverter();

  @override
  DateTime? fromJson(Timestamp? json) => json?.toDate();

  @override
  Timestamp? toJson(DateTime? object) =>
      object == null ? null : Timestamp.fromDate(object);
}

@freezed
class CostObjectModel with _$CostObjectModel {
  const factory CostObjectModel(
      {required int amountOwe,
      @TimestampConverter() DateTime? datePaid,
      required String itemDocID,
      @TimestampConverter() DateTime? lastUpdated,
      required bool paid,
      required String uid,
      required String tripDocID}) = _CostObjectModel;

        factory CostObjectModel.fromJson(Map<String, Object?> json)
      => _$CostObjectModelFromJson(json);
}