import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `feed_model.dart` with the code generated by Freezed
part 'feed_model.freezed.dart';
// optional: Since our feedModel class is serializable, we must add this line.
// But if feedModel was not serializable, we could skip it.
part 'feed_model.g.dart';

///Model for database feed

class TimestampConverter implements JsonConverter<DateTime, Timestamp> {
  const TimestampConverter();

  @override
  DateTime fromJson(Timestamp json) => json.toDate();

  @override
  Timestamp toJson(DateTime object) => Timestamp.fromDate(object);
}

class TimestampNullableConverter implements JsonConverter<DateTime?, Timestamp?> {
  const TimestampNullableConverter();

  @override
  DateTime? fromJson(Timestamp? json) => json?.toDate();

  @override
  Timestamp? toJson(DateTime? object) =>
      object == null ? null : Timestamp.fromDate(object);
}

@freezed
class FeedModel with _$FeedModel {
  const factory FeedModel(
      {@TimestampConverter() DateTime? dateCreated,
      required String docID,
      required String message,
      required String tripID}) = _FeedModel;

        factory FeedModel.fromJson(Map<String, Object?> json)
      => _$FeedModelFromJson(json);
}
