import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `notification_model.dart` with the code generated by Freezed
part 'notification_model.freezed.dart';
// optional: Since our notificationModel class is serializable, we must add this line.
// But if notificationModel was not serializable, we could skip it.
part 'notification_model.g.dart';

///Model for database notification

class TimestampConverter implements JsonConverter<DateTime, Timestamp> {
  const TimestampConverter();

  @override
  DateTime fromJson(Timestamp json) => json.toDate();

  @override
  Timestamp toJson(DateTime object) => Timestamp.fromDate(object);
}

class TimestampNullableConverter implements JsonConverter<DateTime?, Timestamp?> {
  const TimestampNullableConverter();

  @override
  DateTime? fromJson(Timestamp? json) => json?.toDate();

  @override
  Timestamp? toJson(DateTime? object) =>
      object == null ? null : Timestamp.fromDate(object);
}

@freezed
class NotificationModel with _$NotificationModel {
  const factory NotificationModel(
      {required String type,
      required String ownerID,
      required bool ispublic,
      @TimestampConverter() DateTime? timestamp,
      required String message,
      required String documentID,
      required String displayName,
      required String fieldID,
      required String firstname,
      required String lastname,
      required String uid,
      required String ownerDisplayName}) = _NotificationModel;

        factory NotificationModel.fromJson(Map<String, Object?> json)
      => _$NotificationModelFromJson(json);
}