const List<String> activityList = <String>[
  'Movie night',
  'Game night',
  'Picnic',
  'Potluck',
  'Bowling',
  'Karaoke',
  'Beach Day',
  'Hiking',
  'Cooking Class',
  'Amusement Park',
  'Paint and Sip',
  'Escape Room',
  'Laser Tag',
  'Paintball',
  'Muesem Day',
  'Mini Golf',
  'Concert',
  'Music Festival',
  'Go-kart Racing',
  'Sports Game',
  'Community Service',
  'DIY Crafts',
  'Brunch',
  'Dinner Date',
  'Hit the Bar',
  'Club Night'
];
const List<String> tripList = <String>[
  'Beach Getaway',
  'City Exploration',
  'Mountain Retreat',
  'Adventure Safari',
  'Historical Tour',
  'Cultural Immersion',
  'Island Paradise',
  'Road Trip Adventure',
  'Winter Wonderland',
  'Wine Tasting Tour',
  'Tropical Rainforest Expedition',
  'Wellness Retreat',
  'Foodie Adventure',
  'Scenic Cruise',
  'Family Fun',
  'Desert Expedition',
  'Ski Resort Getaway'
];
